### ISSUE TITLE
[BUG] Render crash on unenchanted Ancient Books (`AncientBookNBT.getEnchantment()` returned null)

### ISSUE THREAD

**Issue by mosharky** [alfiehanks/Immersive-Enchanting#12]
**Describe the bug**
The on hover widget/tooltip for ancient books seems to break in an EMI recipe screen

**To Reproduce**
- Use EMI
- Get a recipe with an ancient book (Press U or R on an ancient book)
- Hover over the ancient book

**Expected behavior**
To see this:
<img width="454" height="135" alt="Image" src="https://github.com/user-attachments/assets/ab655091-cc06-4f53-aacf-8727d9b99a5a" />

**Log**
I got two different(?) errors:
1. [Error 1](https://gist.github.com/mosharky/5e307b898863e3f02fc5efbab21e5c9d): `java.lang.NullPointerException: Cannot invoke "net.minecraft.world.item.enchantment.Enchantment.m_44704_()" because "enchantment" is null`
2. [Error 2](https://gist.github.com/mosharky/5459cf4494908286fd05a3fbab2b4ec4): `java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceKey.m_135782_()" because the return value of "me.alfie.immersiveenchanting.item.AncientBookNBT.getEnchantment(net.minecraft.world.item.ItemStack)" is null`
3. [Full latest.log](https://gist.github.com/mosharky/5672e97b57d8941bb1ecf66947839e06) (There's a lot of other errors, i think the only relevant ones are what I outlined above)

# Edit
The game crashes with the same error if I have a `immersiveenchanting:ancient_book` in my inventory with no enchantment. Not sure how i missed this: `Cannot invoke "net.minecraft.resources.ResourceKey.m_135782_()" because the return value of "me.alfie.immersiveenchanting.item.AncientBookNBT.getEnchantment(net.minecraft.world.item.ItemStack)" is null`

Do `/give @s immersiveenchanting:ancient_book` to reproduce. I'm assuming some UI rendering thing can't handle the null value that getEnchantment() returns if there isn't an enchantment.

**Screenshots**
## No error before hovering over the ancient book:
<img width="667" height="1032" alt="Image" src="https://github.com/user-attachments/assets/7a5a426c-b07b-4912-95af-8fb62d0bea1a" />

## After hovering:
<img width="2560" height="1369" alt="Image" src="https://github.com/user-attachments/assets/b2c8e214-6c45-45e1-b038-74f1213662b5" />
<img width="639" height="1013" alt="Image" src="https://github.com/user-attachments/assets/840eeb8d-1fbb-48e3-9e1a-9c8399ba9f66" />

**Comment by SiverDX** [comment]
Since this does not happen with the current state on git it's either
- fixed (there were additional changes to the tooltip set up)
- caused by other mods you have installed (besides EMI)

I hovered enchantments within the list on the right, after pressing `U` and an empty ancient book
By default I don't see any anvil recipes though, just the tags category

**Comment by mosharky** [comment]
~~Have you tested for `/give @s immersiveenchanting:ancient_book` with hovering over an empty ancient book?~~ I haven't tested outside of my modpack honestly, so yeah it could be some other incompatibility. I'll come back if its not fixed once you release your changes :)

**Comment by SiverDX** [comment]
> Have you tested for `/give @s immersiveenchanting:ancient_book` with hovering over an empty ancient book? I haven't tested outside of my modpack honestly, so yeah it could be some other incompatibility. I'll come back if its not fixed once you release your changes :)

just as a quick note, this is not my mod

as I mentioned though, I tested it with an empty ancient book
(I used your command to get it)

**Comment by mosharky** [comment]
oh shoot, not sure how i missed both that you already mentioned it and that you're not a dev. sorry!

**Comment by alfiehanks** [comment]
Should be fixed now
